// User Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// User Register
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// User Profile
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

// Users List (Admin)
export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';

// Seller Applications
export const SELLER_APPLICATION_REQUEST = 'SELLER_APPLICATION_REQUEST';
export const SELLER_APPLICATION_SUCCESS = 'SELLER_APPLICATION_SUCCESS';
export const SELLER_APPLICATION_FAIL = 'SELLER_APPLICATION_FAIL';

export const SELLER_APPLICATIONS_LIST_REQUEST = 'SELLER_APPLICATIONS_LIST_REQUEST';
export const SELLER_APPLICATIONS_LIST_SUCCESS = 'SELLER_APPLICATIONS_LIST_SUCCESS';
export const SELLER_APPLICATIONS_LIST_FAIL = 'SELLER_APPLICATIONS_LIST_FAIL';

// Services List
export const SERVICES_LIST_REQUEST = 'SERVICES_LIST_REQUEST';
export const SERVICES_LIST_SUCCESS = 'SERVICES_LIST_SUCCESS';
export const SERVICES_LIST_FAIL = 'SERVICES_LIST_FAIL';

// Service Detail
export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL';

// Seller Services
export const SELLER_SERVICES_REQUEST = 'SELLER_SERVICES_REQUEST';
export const SELLER_SERVICES_SUCCESS = 'SELLER_SERVICES_SUCCESS';
export const SELLER_SERVICES_FAIL = 'SELLER_SERVICES_FAIL';

// Orders
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAIL = 'ORDERS_FAIL';

// Chat
export const CHAT_REQUEST = 'CHAT_REQUEST';
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';
